version: '9'
name: HashbangOS
type: release
variant: user
datetime: 1564341863
host: android
user: build
platform:
  ref: android-9.0.0_r45
  extra_remotes:
  - name: github
    fetch: https://github.com/
  - name: gitlab
    fetch: https://gitlab.com/
  extra_projects:
  - name: fdroid/fdroidclient
    groups: device
    path: packages/apps/F-Droid
    remote: gitlab
    revision: refs/tags/1.7
  - name: fdroid/privileged-extension
    groups: device
    path: packages/apps/F-DroidPrivilegedExtension
    remote: gitlab
    revision: refs/tags/0.2.9
  - name: anestisb/android-prepare-vendor
    groups: device
    path: vendor/android-prepare-vendor
    remote: github
    revision: refs/heads/master
  - name: stevesoltys/backup
    groups: device
    path: packages/apps/Backup
    remote: github
    revision: refs/heads/master
  - name: GrapheneOS/platform_external_chromium
    groups: device
    path: external/chromium
    remote: github
    revision: refs/heads/pie
  - name: GrapheneOS/platform_packages_apps_Updater
    groups: device
    path: packages/apps/Updater
    remote: github
    revision: refs/heads/pie
  remove_paths:
  - external/chromium-webview
  - packages/apps/Calendar
  - packages/apps/QuickSearchBox
  - packages/apps/Browser2
  - platform/prebuilts/qemu-kernel
  - platform/developers/samples/android
  - platform/developers/demos
  - device/generic/car
  - device/generic/qemu
  - device/generic/goldfish
  - device/generic/goldfish-opengl
  - device/lenaro/bootloader/arm-trusted-firmware
  - device/lenaro/bootloader/edk2
  - device/lenaro/bootloader/OpenPlatformPkg
  - device/lenaro/hikey
  - device/lenaro/hikey-kernel
  - device/lenaro/
  - device/google/atv
  - device/google/contexthub
  - device/google/cuttlefish
  - device/google/cuttlefish_kernel
  - device/google/cuttlefish_sepolicy
  - device/google/cuttlefish_common
  - device/google/crosshatch-kernel
  - device/google/wahoo-kernel
  - device/google/marlin-kernel
  - device/google/muskie
  - device/generic/mips
  - device/google/hikey-kernel
  - device/generic/mips64
  - device/generic/mini-emulator-arm64
  - device/generic/mini-emulator-armv7-a-neon
  - device/generic/mini-emulator-mips
  - device/generic/mini-emulator-mips64
  - device/generic/mini-emulator-x86
  - device/generic/mini-emulator-x86_64
  - device/google/accessory/arduino
  - device/google/accessory/demokit
  remove_groups:
  - darwin
  patches:
  - platform/accept-sdk-licenses.patch
  - platform/add-backup.patch
  - platform/add-chromium.patch
  - platform/add-determinism.patch
  - platform/add-fdroid.patch
  - platform/add-updater.patch
  - platform/fix-devicenames.patch
  - platform/remove-browser2.patch
  - platform/remove-calendar.patch
  - platform/remove-quicksearch.patch
  - platform/remove-webview.patch
apps:
  chromium:
    version: 76.0.3772.1
    src_ref: 81a47ce765daab7199c94a0237dc5b86c49ec5e2
    depot_tools_ref: 8dfc0bce4ac7aeb9b03f0783fe0a22660ea4d796
devices:
  crosshatch:
    global:
      kernel_name: crosshatch
      kernel_ref: origin/android-msm-crosshatch-4.9-pie-qpr2
      kernel_repo: kernel/manifest
      avb_mode: vbmeta_chained
      factory_build: PQ3A.190705.003
      factory_hash: e59cf7a412e48d0f78463a67dc0085d98b811026d7c593b8d61925c2d9895e02
    verizon:
      factory_hash: 0933f2080c5bba78f2858c892ec899cda67c6c01373a25bbcae013fb906a7fc6
      factory_build: PQ3A.190605.004.A1
    docomo:
      factory_build: PQ1A.181205.006.A1
      factory_hash: 99bead334525f4d26ef5777ebc910648674597e1322a2a95e9e2d4f9df5d69cf
  blueline:
    global:
      kernel_name: crosshatch
      kernel_ref: origin/android-msm-crosshatch-4.9-pie-qpr2
      kernel_repo: kernel/manifest
      avb_mode: vbmeta_chained
      factory_build: PQ3A.190705.003
      factory_hash: c14bfb79b6660398f0454279b98ab45ace896e115c462643c0685089f5f1758f
    verizon:
      factory_build: PQ3A.190605.004.A1
      factory_hash: da940910bf3ac99af6ae53be3971698737ba7cb86f42b4d19e67078fd19d7a58
    docomo:
      factory_build: PQ1A.181205.006.A1
      factory_hash: e0442d3b0a9e5636f4979b5780b6173635fe73917e88ffe1b9d36c2bc45aa7bc
  taimen:
    global:
      kernel_name: wahoo
      kernel_ref: android-msm-wahoo-4.4-pie-qpr1
      kernel_repo: kernel/msm
      avb_mode: vbmeta_simple
      factory_build: PQ3A.190705.001
      factory_hash: 884e074c374080550450d6b9356e9732043d38a5e4957aedcac9c82ec6f20fb5
    telstra:
      factory_build: PPR1.180610.011
      factory_hash: 9f0cb004c3b42789c150293aa6a6eecb0f289324ce1403befde93b106da59829
  walleye:
    global:
      kernel_name: wahoo
      kernel_ref: android-msm-wahoo-4.4-pie-qpr1
      kernel_repo: kernel/msm
      avb_mode: vbmeta_simple
      factory_build: PQ3A.190705.001
      factory_hash: cc471c8c7ffaa899e30438fa30b8d33b92b12a3c92d3e592c53bfc5983de205b
    telstra:
      factory_build: PPR1.180610.011
      factory_hash: 0fbd304845b6a1e8c5960deedb70aab0f804a4b1bb93242b3bbcdad586982769
  marlin:
    global:
      kernel_name: marlin
      kernel_ref: android-msm-marlin-3.18-pie-qpr1-s2
      kernel_repo: kernel/msm
      avb_mode: verity_only
      factory_build: PQ3A.190705.001
      factory_hash: 522f27c4d50055f6402ca9d4d62fb07425e3af7c4766b647a4096ce3041984ba
    telus:
      factory_build: PPR1.181005.003.A1
      factory_hash: 960a173f0f84e2c3c0c5d96643e6ca3f99d5a898a932c6e3a62c52282d6fb3f4
    verizon:
      factory_build: PPR2.180905.006.A1
      factory_hash: a78fe26434e04f8d5015bab79f717fc7b03b13286370b079b7e96d1f7562512a
  sailfish:
    global:
      kernel_name: marlin
      kernel_ref: android-msm-marlin-3.18-pie-qpr1-s2
      kernel_repo: kernel/msm
      avb_mode: verity_only
      factory_build: PQ3A.190705.001
      factory_hash: 7f9ff7f7fd447ecb9a3724878c71afc8ea64969cb085b900ce6827da3cc97a1a
    telus:
      factory_build: PPR1.181005.003.A1
      factory_hash: 6a2c3b69a43f93e576f953d7c8368648bd26f7d23667556a65af40282a72f7af
    verizon:
      factory_build: PPR2.180905.006.A1
      factory_hash: b063909b211beea28e6879a12db1dade1eb4c007900082c10ea160f15c6feae7
